version: "3.8"

services:
  mongodb:
    image: mongo:7
    container_name: mongo
    restart: unless-stopped
    volumes:
      - mongo-data:/data/db

  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8888:5050"
    env_file: ./backend/.env
    depends_on:
      - mongodb
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: sh -c "npm install && npm start" # Thực thi npm install trước khi start

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "8889:80"
    depends_on:
      - backend
    volumes:
      - ./frontend:/usr/share/nginx/html

volumes:
  mongo-data:
    